#!/usr/bin/env python3
# coding=utf-8

from shuttle.cli import __main__ as cli_main

XPRIVATE_KEY = "205b15f70e253399da90b127b074ea02904594be9d54678207872ec1ba31ee51ef4490504bd2b6f997113671892458830d" \
               "e09518e6bd5958d5d5dd97624cfa4b"

FUND_RAW = "eyJmZWUiOiAxMDAwMDAwMCwgImd1aWQiOiAiZjBlZDZkZGQtOWQ2Yi00OWZkLTg4NjYtYTUyZDEwODNhMTNiIiwgInVuc2lnbmVkIj" \
           "ogW3siZGF0YXMiOiBbImIxYzVlYTFkNjAwNjY0Y2U4MTAwNzMxNmQ2Zjg5NThlMjQ4ZWZhNjk3YWRhN2Q0M2E4YzI2YjJkNjE1NjAx" \
           "NDgiXSwgInB1YmxpY19rZXkiOiAiOTFmZjdmNTI1ZmY0MDg3NGM0ZjQ3ZjBjYWI0MmU0NmUzYmY1M2FkYWQ1OWFkZWY5NTU4YWQxYj" \
           "Y0NDhmMjJlMiIsICJuZXR3b3JrIjogIm1haW5uZXQiLCAicGF0aCI6ICJtLzQ0LzE1My8xLzAvMSJ9LCB7ImRhdGFzIjogWyIyNTFm" \
           "YmQ4YTAzMmM3MmJmMjkwN2VjNGFmYzk1ZGYxZTE2Mzg5NDZiODE5MGQwYjIxZTk1MjA2YmU2YzZhOTYyIl0sICJwdWJsaWNfa2V5Ij" \
           "ogIjkxZmY3ZjUyNWZmNDA4NzRjNGY0N2YwY2FiNDJlNDZlM2JmNTNhZGFkNTlhZGVmOTU1OGFkMWI2NDQ4ZjIyZTIiLCAibmV0d29y" \
           "ayI6ICJtYWlubmV0IiwgInBhdGgiOiAibS80NC8xNTMvMS8wLzEifV0sICJoYXNoIjogImM2YjMyYjk1ODEwYTEwMDIzZDA3ODk2OD" \
           "czNTI3NGQwMWU4YjVmZjhjNTU3NjNkODM3OGZhZjZhZjI5YTY2NjYiLCAicmF3IjogIjA3MDEwMDAyMDE2MTAxNWY4MWU1MGUxMmY4" \
           "MjM2ZjkxYzg4NDJkM2Y0OTU1MDJiOTc1MmZjMzVkMDE1MDA5MWVhNWIyYzI2NjA1MTVjM2I1ZjM3ZGVhNjJlZmQyOTY1MTc0Yjg0Ym" \
           "JiNTlhMGJkMGE2NzFjZjVmYjI4NTczMDNmZmQ3N2MxYjQ4MmI4NGJkZmE4Y2JkYmMzZjQwMjAxMDExNjAwMTQyY2RhNGY5OWVhODEx" \
           "MmU2ZmE2MWNkZDI2MTU3ZWQ2ZGM0MDgzMzJhMjIwMTIwOTFmZjdmNTI1ZmY0MDg3NGM0ZjQ3ZjBjYWI0MmU0NmUzYmY1M2FkYWQ1OW" \
           "FkZWY5NTU4YWQxYjY0NDhmMjJlMjAxNjAwMTVlM2ZiZjI0YjQwYzlhNzhiNWY3NmJlZTVlNmIyNDI4YTllYzU4YWJkNjQwNDk1ZDQ5" \
           "ODQ0MDk2MjQxYTJjMDM2NWZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZm" \
           "ZmZmY4MGRkOTZmZDA4MDEwMTE2MDAxNDJjZGE0Zjk5ZWE4MTEyZTZmYTYxY2RkMjYxNTdlZDZkYzQwODMzMmEyMjAxMjA5MWZmN2Y1" \
           "MjVmZjQwODc0YzRmNDdmMGNhYjQyZTQ2ZTNiZjUzYWRhZDU5YWRlZjk1NThhZDFiNjQ0OGYyMmUyMDMwMWFjMDFmMzdkZWE2MmVmZD" \
           "I5NjUxNzRiODRiYmI1OWEwYmQwYTY3MWNmNWZiMjg1NzMwM2ZmZDc3YzFiNDgyYjg0YmRmNjQwMTg4MDEwMTY0MjA5MWZmN2Y1MjVm" \
           "ZjQwODc0YzRmNDdmMGNhYjQyZTQ2ZTNiZjUzYWRhZDU5YWRlZjk1NThhZDFiNjQ0OGYyMmUyMjBhYzEzYzBiYjE0NDU0MjNhNjQxNz" \
           "U0MTgyZDUzZjA2NzdjZDQzNTFhMGU3NDNlNmYxMGIzNTEyMmMzZDdlYTAxMjAzYTI2ZGE4MmVhZDE1YTgwNTMzYTAyNjk2NjU2YjE0" \
           "YjVkYmZkODRlYjE0NzkwZjJlMWJlNWU5ZTQ1ODIwZWViNzQxZjU0N2E2NDE2MDAwMDAwNTU3YWE4ODg1MzdhN2NhZTdjYWM2MzFmMD" \
           "AwMDAwNTM3YWNkOWY2OTcyYWU3Y2FjMDBjMDAwMDEzZWYzN2RlYTYyZWZkMjk2NTE3NGI4NGJiYjU5YTBiZDBhNjcxY2Y1ZmIyODU3" \
           "MzAzZmZkNzdjMWI0ODJiODRiZGZjNGNhZGJjM2Y0MDIwMTE2MDAxNDJjZGE0Zjk5ZWE4MTEyZTZmYTYxY2RkMjYxNTdlZDZkYzQwOD" \
           "MzMmEwMDAxM2RmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmODBi" \
           "MGI0ZjgwODAxMTYwMDE0MmNkYTRmOTllYTgxMTJlNmZhNjFjZGQyNjE1N2VkNmRjNDA4MzMyYTAwIiwgInNpZ25hdHVyZXMiOiBbXS" \
           "wgIm5ldHdvcmsiOiAibWFpbm5ldCIsICJ0eXBlIjogImJ5dG9tX2Z1bmRfdW5zaWduZWQifQ"

FUND_SIGNED = "eyJmZWUiOiAxMDAwMDAwMCwgImd1aWQiOiAiZjBlZDZkZGQtOWQ2Yi00OWZkLTg4NjYtYTUyZDEwODNhMTNiIiwgInJhdyI6ICI" \
              "wNzAxMDAwMjAxNjEwMTVmODFlNTBlMTJmODIzNmY5MWM4ODQyZDNmNDk1NTAyYjk3NTJmYzM1ZDAxNTAwOTFlYTViMmMyNjYwNT" \
              "E1YzNiNWYzN2RlYTYyZWZkMjk2NTE3NGI4NGJiYjU5YTBiZDBhNjcxY2Y1ZmIyODU3MzAzZmZkNzdjMWI0ODJiODRiZGZhOGNiZ" \
              "GJjM2Y0MDIwMTAxMTYwMDE0MmNkYTRmOTllYTgxMTJlNmZhNjFjZGQyNjE1N2VkNmRjNDA4MzMyYTIyMDEyMDkxZmY3ZjUyNWZm" \
              "NDA4NzRjNGY0N2YwY2FiNDJlNDZlM2JmNTNhZGFkNTlhZGVmOTU1OGFkMWI2NDQ4ZjIyZTIwMTYwMDE1ZTNmYmYyNGI0MGM5YTc" \
              "4YjVmNzZiZWU1ZTZiMjQyOGE5ZWM1OGFiZDY0MDQ5NWQ0OTg0NDA5NjI0MWEyYzAzNjVmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZm" \
              "ZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmODBkZDk2ZmQwODAxMDExNjAwMTQyY2RhNGY5OWVhODExM" \
              "mU2ZmE2MWNkZDI2MTU3ZWQ2ZGM0MDgzMzJhMjIwMTIwOTFmZjdmNTI1ZmY0MDg3NGM0ZjQ3ZjBjYWI0MmU0NmUzYmY1M2FkYWQ1" \
              "OWFkZWY5NTU4YWQxYjY0NDhmMjJlMjAzMDFhYzAxZjM3ZGVhNjJlZmQyOTY1MTc0Yjg0YmJiNTlhMGJkMGE2NzFjZjVmYjI4NTc" \
              "zMDNmZmQ3N2MxYjQ4MmI4NGJkZjY0MDE4ODAxMDE2NDIwOTFmZjdmNTI1ZmY0MDg3NGM0ZjQ3ZjBjYWI0MmU0NmUzYmY1M2FkYW" \
              "Q1OWFkZWY5NTU4YWQxYjY0NDhmMjJlMjIwYWMxM2MwYmIxNDQ1NDIzYTY0MTc1NDE4MmQ1M2YwNjc3Y2Q0MzUxYTBlNzQzZTZmM" \
              "TBiMzUxMjJjM2Q3ZWEwMTIwM2EyNmRhODJlYWQxNWE4MDUzM2EwMjY5NjY1NmIxNGI1ZGJmZDg0ZWIxNDc5MGYyZTFiZTVlOWU0" \
              "NTgyMGVlYjc0MWY1NDdhNjQxNjAwMDAwMDU1N2FhODg4NTM3YTdjYWU3Y2FjNjMxZjAwMDAwMDUzN2FjZDlmNjk3MmFlN2NhYzA" \
              "wYzAwMDAxM2VmMzdkZWE2MmVmZDI5NjUxNzRiODRiYmI1OWEwYmQwYTY3MWNmNWZiMjg1NzMwM2ZmZDc3YzFiNDgyYjg0YmRmYz" \
              "RjYWRiYzNmNDAyMDExNjAwMTQyY2RhNGY5OWVhODExMmU2ZmE2MWNkZDI2MTU3ZWQ2ZGM0MDgzMzJhMDAwMTNkZmZmZmZmZmZmZ" \
              "mZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZjgwYjBiNGY4MDgwMTE2MDAxNDJj" \
              "ZGE0Zjk5ZWE4MTEyZTZmYTYxY2RkMjYxNTdlZDZkYzQwODMzMmEwMCIsICJoYXNoIjogImM2YjMyYjk1ODEwYTEwMDIzZDA3ODk" \
              "2ODczNTI3NGQwMWU4YjVmZjhjNTU3NjNkODM3OGZhZjZhZjI5YTY2NjYiLCAidW5zaWduZWQiOiBbeyJkYXRhcyI6IFsiYjFjNW" \
              "VhMWQ2MDA2NjRjZTgxMDA3MzE2ZDZmODk1OGUyNDhlZmE2OTdhZGE3ZDQzYThjMjZiMmQ2MTU2MDE0OCJdLCAicHVibGljX2tle" \
              "SI6ICI5MWZmN2Y1MjVmZjQwODc0YzRmNDdmMGNhYjQyZTQ2ZTNiZjUzYWRhZDU5YWRlZjk1NThhZDFiNjQ0OGYyMmUyIiwgIm5l" \
              "dHdvcmsiOiAibWFpbm5ldCIsICJwYXRoIjogIm0vNDQvMTUzLzEvMC8xIn0sIHsiZGF0YXMiOiBbIjI1MWZiZDhhMDMyYzcyYmY" \
              "yOTA3ZWM0YWZjOTVkZjFlMTYzODk0NmI4MTkwZDBiMjFlOTUyMDZiZTZjNmE5NjIiXSwgInB1YmxpY19rZXkiOiAiOTFmZjdmNT" \
              "I1ZmY0MDg3NGM0ZjQ3ZjBjYWI0MmU0NmUzYmY1M2FkYWQ1OWFkZWY5NTU4YWQxYjY0NDhmMjJlMiIsICJuZXR3b3JrIjogIm1ha" \
              "W5uZXQiLCAicGF0aCI6ICJtLzQ0LzE1My8xLzAvMSJ9XSwgIm5ldHdvcmsiOiAibWFpbm5ldCIsICJzaWduYXR1cmVzIjogW1si" \
              "ZGZkYTRhN2E3Mzk1MDhlYWZiNjc4NDZhYWEyOGJlOTcwMTdjNTY0MmQ1ZDNjNWNlMzY4NjA1ZTExZTBmY2ExZTM1OWQ0ZWRmMmM" \
              "xMTJhNTI4NjIyZDRmYzc1OTQxMTFjNWFkOTIxY2VlNjczNzhjNjJhNmMwZGIyZGQzNzkyMDEiXSwgWyI4Y2ZlNWRmYTM5ZmIyM2" \
              "VlNmMxNWViNWNjYjgwMDlmMzI5NDhjMmMxNTliMTZiNWNhYjhiN2IxNzk5MzZhZTU5MDAxNzNmOTZmZjc2YjdmYjBiNDU4Y2RiN" \
              "zAyMzBhYmFkYjhmNjlkNmY2ZWU4NDIyMjM5ZWNiOTA0OWNlYTMwZiJdXSwgInR5cGUiOiAiYnl0b21fZnVuZF9zaWduZWQifQ=="

CLAIM_RAW = \
      "eyJmZWUiOiAxMDAwMDAwMCwgImd1aWQiOiAiZjBlZDZkZGQtOWQ2Yi00OWZkLTg4NjYtYTUyZDEwODNhMTNiIiwgInVuc2lnbmVkIjogW3s" \
      "iZGF0YXMiOiBbIjg0MGYwZjM5MTFiOTllY2NlODk0MjA0OWFhYjY4NjEzMmE5MTAzNTBiZTAxNDY0MTU1YzkzM2ZjMWE5Y2NmZjQiXSwgIm" \
      "5ldHdvcmsiOiAibWFpbm5ldCIsICJwYXRoIjogbnVsbH0sIHsiZGF0YXMiOiBbIjg2ZGFiNjAwZWFjMDMxYjM4YjE2YmQ1NGQzMjMwYjgyN" \
      "WUwYjI2YmNkZGZkZGJhNTdjODBhZDNmNjI4YTllYTIiXSwgInB1YmxpY19rZXkiOiAiOTFmZjdmNTI1ZmY0MDg3NGM0ZjQ3ZjBjYWI0MmU0" \
      "NmUzYmY1M2FkYWQ1OWFkZWY5NTU4YWQxYjY0NDhmMjJlMiIsICJuZXR3b3JrIjogIm1haW5uZXQiLCAicGF0aCI6ICJtLzQ0LzE1My8xLzA" \
      "vMSJ9XSwgImhhc2giOiAiZTg5OWVjNzlhN2IxYTk0MzFjYjczNWMxYmMxYmNhYzg1MDJjZjZkYmY3NTA0ODdjMzcxYjQ0NDFkNTUyNmVjNi" \
      "IsICJyYXciOiAiMDcwMTAwMDIwMWQwMDEwMWNkMDEzZmJmMjRiNDBjOWE3OGI1Zjc2YmVlNWU2YjI0MjhhOWVjNThhYmQ2NDA0OTVkNDk4N" \
      "DQwOTYyNDFhMmMwMzY1ZjM3ZGVhNjJlZmQyOTY1MTc0Yjg0YmJiNTlhMGJkMGE2NzFjZjVmYjI4NTczMDNmZmQ3N2MxYjQ4MmI4NGJkZjY0" \
      "MDAwMTg4MDEwMTY0MjA5MWZmN2Y1MjVmZjQwODc0YzRmNDdmMGNhYjQyZTQ2ZTNiZjUzYWRhZDU5YWRlZjk1NThhZDFiNjQ0OGYyMmUyMjB" \
      "hYzEzYzBiYjE0NDU0MjNhNjQxNzU0MTgyZDUzZjA2NzdjZDQzNTFhMGU3NDNlNmYxMGIzNTEyMmMzZDdlYTAxMjAyYjlhNTk0OWY1NTQ2Zj" \
      "YzYTI1M2U0MWNkYTZiZmZkZWRiNTI3Mjg4YTdlMjRlZDk1M2Y1YzI2ODBjNzBkNmZmNzQxZjU0N2E2NDE2MDAwMDAwNTU3YWE4ODg1MzdhN" \
      "2NhZTdjYWM2MzFmMDAwMDAwNTM3YWNkOWY2OTcyYWU3Y2FjMDBjMDAxMDAwMTYwMDE1ZTNmYmYyNGI0MGM5YTc4YjVmNzZiZWU1ZTZiMjQy" \
      "OGE5ZWM1OGFiZDY0MDQ5NWQ0OTg0NDA5NjI0MWEyYzAzNjVmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZ" \
      "mZmZmZmZmZmZmZmZmZmZmZmZmODBkZDk2ZmQwODAxMDExNjAwMTQyY2RhNGY5OWVhODExMmU2ZmE2MWNkZDI2MTU3ZWQ2ZGM0MDgzMzJhMj" \
      "IwMTIwOTFmZjdmNTI1ZmY0MDg3NGM0ZjQ3ZjBjYWI0MmU0NmUzYmY1M2FkYWQ1OWFkZWY5NTU4YWQxYjY0NDhmMjJlMjAyMDEzOWYzN2RlY" \
      "TYyZWZkMjk2NTE3NGI4NGJiYjU5YTBiZDBhNjcxY2Y1ZmIyODU3MzAzZmZkNzdjMWI0ODJiODRiZGY2NDAxMTYwMDE0MTFiYzE5MGY0ZWJl" \
      "M2E2ZGRjYmM3YWVmNjk3M2FjNGE4OTNiNDQ1NjAwMDEzZGZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZ" \
      "mZmZmZmZmZmZmZmZmZmZmZmY4MGIwYjRmODA4MDExNjAwMTQyY2RhNGY5OWVhODExMmU2ZmE2MWNkZDI2MTU3ZWQ2ZGM0MDgzMzJhMDAiLC" \
      "Aic2VjcmV0IjogIkhlbGxvIE1laGVyZXQhIiwgIm5ldHdvcmsiOiAibWFpbm5ldCIsICJzaWduYXR1cmVzIjogW10sICJ0eXBlIjogImJ5d" \
      "G9tX2NsYWltX3Vuc2lnbmVkIn0="

CLAIM_SIGNED = \
         "eyJmZWUiOiAxMDAwMDAwMCwgImd1aWQiOiAiZjBlZDZkZGQtOWQ2Yi00OWZkLTg4NjYtYTUyZDEwODNhMTNiIiwgInJhdyI6ICIwNzAx" \
         "MDAwMjAxZDAwMTAxY2QwMTNmYmYyNGI0MGM5YTc4YjVmNzZiZWU1ZTZiMjQyOGE5ZWM1OGFiZDY0MDQ5NWQ0OTg0NDA5NjI0MWEyYzAz" \
         "NjVmMzdkZWE2MmVmZDI5NjUxNzRiODRiYmI1OWEwYmQwYTY3MWNmNWZiMjg1NzMwM2ZmZDc3YzFiNDgyYjg0YmRmNjQwMDAxODgwMTAx" \
         "NjQyMDkxZmY3ZjUyNWZmNDA4NzRjNGY0N2YwY2FiNDJlNDZlM2JmNTNhZGFkNTlhZGVmOTU1OGFkMWI2NDQ4ZjIyZTIyMGFjMTNjMGJi" \
         "MTQ0NTQyM2E2NDE3NTQxODJkNTNmMDY3N2NkNDM1MWEwZTc0M2U2ZjEwYjM1MTIyYzNkN2VhMDEyMDJiOWE1OTQ5ZjU1NDZmNjNhMjUz" \
         "ZTQxY2RhNmJmZmRlZGI1MjcyODhhN2UyNGVkOTUzZjVjMjY4MGM3MGQ2ZmY3NDFmNTQ3YTY0MTYwMDAwMDA1NTdhYTg4ODUzN2E3Y2Fl" \
         "N2NhYzYzMWYwMDAwMDA1MzdhY2Q5ZjY5NzJhZTdjYWMwMGMwMDEwMDAxNjAwMTVlM2ZiZjI0YjQwYzlhNzhiNWY3NmJlZTVlNmIyNDI4" \
         "YTllYzU4YWJkNjQwNDk1ZDQ5ODQ0MDk2MjQxYTJjMDM2NWZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZm" \
         "ZmZmZmZmZmZmZmZmZmZmZmZmZmY4MGRkOTZmZDA4MDEwMTE2MDAxNDJjZGE0Zjk5ZWE4MTEyZTZmYTYxY2RkMjYxNTdlZDZkYzQwODMz" \
         "MmEyMjAxMjA5MWZmN2Y1MjVmZjQwODc0YzRmNDdmMGNhYjQyZTQ2ZTNiZjUzYWRhZDU5YWRlZjk1NThhZDFiNjQ0OGYyMmUyMDIwMTM5" \
         "ZjM3ZGVhNjJlZmQyOTY1MTc0Yjg0YmJiNTlhMGJkMGE2NzFjZjVmYjI4NTczMDNmZmQ3N2MxYjQ4MmI4NGJkZjY0MDExNjAwMTQxMWJj" \
         "MTkwZjRlYmUzYTZkZGNiYzdhZWY2OTczYWM0YTg5M2I0NDU2MDAwMTNkZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZm" \
         "ZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZjgwYjBiNGY4MDgwMTE2MDAxNDJjZGE0Zjk5ZWE4MTEyZTZmYTYxY2RkMjYxNTdlZDZk" \
         "YzQwODMzMmEwMCIsICJoYXNoIjogImU4OTllYzc5YTdiMWE5NDMxY2I3MzVjMWJjMWJjYWM4NTAyY2Y2ZGJmNzUwNDg3YzM3MWI0NDQx" \
         "ZDU1MjZlYzYiLCAidW5zaWduZWQiOiBbeyJkYXRhcyI6IFsiODQwZjBmMzkxMWI5OWVjY2U4OTQyMDQ5YWFiNjg2MTMyYTkxMDM1MGJl" \
         "MDE0NjQxNTVjOTMzZmMxYTljY2ZmNCJdLCAibmV0d29yayI6ICJtYWlubmV0IiwgInBhdGgiOiBudWxsfSwgeyJkYXRhcyI6IFsiODZk" \
         "YWI2MDBlYWMwMzFiMzhiMTZiZDU0ZDMyMzBiODI1ZTBiMjZiY2RkZmRkYmE1N2M4MGFkM2Y2MjhhOWVhMiJdLCAicHVibGljX2tleSI6" \
         "ICI5MWZmN2Y1MjVmZjQwODc0YzRmNDdmMGNhYjQyZTQ2ZTNiZjUzYWRhZDU5YWRlZjk1NThhZDFiNjQ0OGYyMmUyIiwgIm5ldHdvcmsi" \
         "OiAibWFpbm5ldCIsICJwYXRoIjogIm0vNDQvMTUzLzEvMC8xIn1dLCAibmV0d29yayI6ICJtYWlubmV0IiwgInNpZ25hdHVyZXMiOiBb" \
         "WyI0ODY1NmM2YzZmMjA0ZDY1Njg2NTcyNjU3NDIxIiwgIjdjNjA5OWY1MTIzYWIwZThjZTgzYWZmNDVmZTgxMWVmNmI0OTBjNjg3YWU3" \
         "ZWQ0NTc5ZDQ3NDhjMzk2ZjM5MGNjMDE4Mzk5NjRmYTU2MmFhMzg0M2IwMDBhYzIzOTcxZjEzNWJiMDczMDBiMDI2YjQ1OTdjNWMyNGNj" \
         "ZGJiNDA5IiwgIiJdLCBbIjRiYTFiZDA5NjYyMmJiNjdjMmU3MGI0ZDlmZDhhOWU5MmNiMjk5YjM4MDRlZTQzNzNhMzU3Y2FhMjNkNWMz" \
         "NDQ5MzJjNjM4ZmU4OGM4MDA3NDEzNTMyYWRjMjgyZWVkYzQyNjg2NjZiMDg3ODk2ZWExYWFjNTFlNWNhODQyODA3Il1dLCAidHlwZSI6" \
         "ICJieXRvbV9jbGFpbV9zaWduZWQifQ=="

REFUND_RAW = "eyJmZWUiOiAxMDAwMDAwMCwgImd1aWQiOiAiZjBlZDZkZGQtOWQ2Yi00OWZkLTg4NjYtYTUyZDEwODNhMTNiIiwgInVuc2lnbmVk" \
             "IjogW3siZGF0YXMiOiBbIjQ5NGVlNzc2OTBhYzJhYjUxZTZkZTRkYWMyZWJhMmQzNTc3MTc0MzEyZWQwYTIyMjQ5NGE5OTVlMjhm" \
             "ZmY4NDYiXSwgIm5ldHdvcmsiOiAibWFpbm5ldCIsICJwYXRoIjogbnVsbH0sIHsiZGF0YXMiOiBbImVjYWJhNDAxYTZkZjljZmZi" \
             "ZWQzN2QxYWJjZjIzYjkxYjNjODRlYzdhYTk0MTFkNDgxY2JlZjJlNDM3ZWY3YjEiXSwgInB1YmxpY19rZXkiOiAiOTFmZjdmNTI1" \
             "ZmY0MDg3NGM0ZjQ3ZjBjYWI0MmU0NmUzYmY1M2FkYWQ1OWFkZWY5NTU4YWQxYjY0NDhmMjJlMiIsICJuZXR3b3JrIjogIm1haW5u" \
             "ZXQiLCAicGF0aCI6ICJtLzQ0LzE1My8xLzAvMSJ9XSwgImhhc2giOiAiMDY5YWU0NDg2MDQ3ZWQzMTQzMjkxYWFjNzVkM2FmNDhk" \
             "MTI4MzZkMGI1ODEyNzg3MTc3ZGM0MGJiOTY1YzkwZiIsICJyYXciOiAiMDcwMTAwMDIwMWQwMDEwMWNkMDEzZmJmMjRiNDBjOWE3" \
             "OGI1Zjc2YmVlNWU2YjI0MjhhOWVjNThhYmQ2NDA0OTVkNDk4NDQwOTYyNDFhMmMwMzY1ZjM3ZGVhNjJlZmQyOTY1MTc0Yjg0YmJi" \
             "NTlhMGJkMGE2NzFjZjVmYjI4NTczMDNmZmQ3N2MxYjQ4MmI4NGJkZjY0MDAwMTg4MDEwMTY0MjA5MWZmN2Y1MjVmZjQwODc0YzRm" \
             "NDdmMGNhYjQyZTQ2ZTNiZjUzYWRhZDU5YWRlZjk1NThhZDFiNjQ0OGYyMmUyMjBhYzEzYzBiYjE0NDU0MjNhNjQxNzU0MTgyZDUz" \
             "ZjA2NzdjZDQzNTFhMGU3NDNlNmYxMGIzNTEyMmMzZDdlYTAxMjAyYjlhNTk0OWY1NTQ2ZjYzYTI1M2U0MWNkYTZiZmZkZWRiNTI3" \
             "Mjg4YTdlMjRlZDk1M2Y1YzI2ODBjNzBkNmZmNzQxZjU0N2E2NDE2MDAwMDAwNTU3YWE4ODg1MzdhN2NhZTdjYWM2MzFmMDAwMDAw" \
             "NTM3YWNkOWY2OTcyYWU3Y2FjMDBjMDAxMDAwMTYwMDE1ZTNmYmYyNGI0MGM5YTc4YjVmNzZiZWU1ZTZiMjQyOGE5ZWM1OGFiZDY0" \
             "MDQ5NWQ0OTg0NDA5NjI0MWEyYzAzNjVmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZm" \
             "ZmZmZmZmZmZmZmZmODBkZDk2ZmQwODAxMDExNjAwMTQyY2RhNGY5OWVhODExMmU2ZmE2MWNkZDI2MTU3ZWQ2ZGM0MDgzMzJhMjIw" \
             "MTIwOTFmZjdmNTI1ZmY0MDg3NGM0ZjQ3ZjBjYWI0MmU0NmUzYmY1M2FkYWQ1OWFkZWY5NTU4YWQxYjY0NDhmMjJlMjAyMDEzOWYz" \
             "N2RlYTYyZWZkMjk2NTE3NGI4NGJiYjU5YTBiZDBhNjcxY2Y1ZmIyODU3MzAzZmZkNzdjMWI0ODJiODRiZGY2NDAxMTYwMDE0MmNk" \
             "YTRmOTllYTgxMTJlNmZhNjFjZGQyNjE1N2VkNmRjNDA4MzMyYTAwMDEzZGZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZm" \
             "ZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmY4MGIwYjRmODA4MDExNjAwMTQyY2RhNGY5OWVhODExMmU2ZmE2MWNkZDI2" \
             "MTU3ZWQ2ZGM0MDgzMzJhMDAiLCAic2lnbmF0dXJlcyI6IFtdLCAibmV0d29yayI6ICJtYWlubmV0IiwgInR5cGUiOiAiYnl0b21f" \
             "cmVmdW5kX3Vuc2lnbmVkIn0="

REFUND_SIGNED = "eyJmZWUiOiAxMDAwMDAwMCwgImd1aWQiOiAiZjBlZDZkZGQtOWQ2Yi00OWZkLTg4NjYtYTUyZDEwODNhMTNiIiwgInJhdyI6I" \
                "CIwNzAxMDAwMjAxZDAwMTAxY2QwMTNmYmYyNGI0MGM5YTc4YjVmNzZiZWU1ZTZiMjQyOGE5ZWM1OGFiZDY0MDQ5NWQ0OTg0ND" \
                "A5NjI0MWEyYzAzNjVmMzdkZWE2MmVmZDI5NjUxNzRiODRiYmI1OWEwYmQwYTY3MWNmNWZiMjg1NzMwM2ZmZDc3YzFiNDgyYjg" \
                "0YmRmNjQwMDAxODgwMTAxNjQyMDkxZmY3ZjUyNWZmNDA4NzRjNGY0N2YwY2FiNDJlNDZlM2JmNTNhZGFkNTlhZGVmOTU1OGFk" \
                "MWI2NDQ4ZjIyZTIyMGFjMTNjMGJiMTQ0NTQyM2E2NDE3NTQxODJkNTNmMDY3N2NkNDM1MWEwZTc0M2U2ZjEwYjM1MTIyYzNkN" \
                "2VhMDEyMDJiOWE1OTQ5ZjU1NDZmNjNhMjUzZTQxY2RhNmJmZmRlZGI1MjcyODhhN2UyNGVkOTUzZjVjMjY4MGM3MGQ2ZmY3ND" \
                "FmNTQ3YTY0MTYwMDAwMDA1NTdhYTg4ODUzN2E3Y2FlN2NhYzYzMWYwMDAwMDA1MzdhY2Q5ZjY5NzJhZTdjYWMwMGMwMDEwMDA" \
                "xNjAwMTVlM2ZiZjI0YjQwYzlhNzhiNWY3NmJlZTVlNmIyNDI4YTllYzU4YWJkNjQwNDk1ZDQ5ODQ0MDk2MjQxYTJjMDM2NWZm" \
                "ZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmY4MGRkOTZmZDA4M" \
                "DEwMTE2MDAxNDJjZGE0Zjk5ZWE4MTEyZTZmYTYxY2RkMjYxNTdlZDZkYzQwODMzMmEyMjAxMjA5MWZmN2Y1MjVmZjQwODc0Yz" \
                "RmNDdmMGNhYjQyZTQ2ZTNiZjUzYWRhZDU5YWRlZjk1NThhZDFiNjQ0OGYyMmUyMDIwMTM5ZjM3ZGVhNjJlZmQyOTY1MTc0Yjg" \
                "0YmJiNTlhMGJkMGE2NzFjZjVmYjI4NTczMDNmZmQ3N2MxYjQ4MmI4NGJkZjY0MDExNjAwMTQyY2RhNGY5OWVhODExMmU2ZmE2" \
                "MWNkZDI2MTU3ZWQ2ZGM0MDgzMzJhMDAwMTNkZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZ" \
                "mZmZmZmZmZmZmZmZmZmZmZmZjgwYjBiNGY4MDgwMTE2MDAxNDJjZGE0Zjk5ZWE4MTEyZTZmYTYxY2RkMjYxNTdlZDZkYzQwOD" \
                "MzMmEwMCIsICJoYXNoIjogIjA2OWFlNDQ4NjA0N2VkMzE0MzI5MWFhYzc1ZDNhZjQ4ZDEyODM2ZDBiNTgxMjc4NzE3N2RjNDB" \
                "iYjk2NWM5MGYiLCAidW5zaWduZWQiOiBbeyJkYXRhcyI6IFsiNDk0ZWU3NzY5MGFjMmFiNTFlNmRlNGRhYzJlYmEyZDM1Nzcx" \
                "NzQzMTJlZDBhMjIyNDk0YTk5NWUyOGZmZjg0NiJdLCAibmV0d29yayI6ICJtYWlubmV0IiwgInBhdGgiOiBudWxsfSwgeyJkY" \
                "XRhcyI6IFsiZWNhYmE0MDFhNmRmOWNmZmJlZDM3ZDFhYmNmMjNiOTFiM2M4NGVjN2FhOTQxMWQ0ODFjYmVmMmU0MzdlZjdiMS" \
                "JdLCAicHVibGljX2tleSI6ICI5MWZmN2Y1MjVmZjQwODc0YzRmNDdmMGNhYjQyZTQ2ZTNiZjUzYWRhZDU5YWRlZjk1NThhZDF" \
                "iNjQ0OGYyMmUyIiwgIm5ldHdvcmsiOiAibWFpbm5ldCIsICJwYXRoIjogIm0vNDQvMTUzLzEvMC8xIn1dLCAibmV0d29yayI6" \
                "ICJtYWlubmV0IiwgInNpZ25hdHVyZXMiOiBbWyI2NWI0ZmNkOWU2ZDU4ZTJhYjlkZGFkYzZmMzMwYzUxOWQzZmNlY2ZlM2QzM" \
                "GE0ZTQ4NDE5OTIwYzlkYmE5ZGM4OGJlNTAzZDdjOWE4MjVkMDliZWNkNjgzODBiNmM0ZTNhZGIwNTQ1ZDg1MWI5NjgxMjhjMD" \
                "hkZGIwMWNkZTcwZCIsICIwMSJdLCBbIjViZDkwNmQ2ODI5YjE2NzljMWI2ZTk4Nzg0OWU1Zjg0MzJhMWRkNzExNGIwMjY5MDh" \
                "mNjc1ZGFmYjlhOTUyNmUyNWE3YTIzZjQ1MWUwODY5NWMxMzNlNjdhODk5MDc5Y2Y3NTQxMGNjMDU1YjkzNzE1OGZjNDczZTgx" \
                "NTQxMzBhIl1dLCAidHlwZSI6ICJieXRvbV9yZWZ1bmRfc2lnbmVkIn0="


# Success template
def success(_):
    return "[{}] {}".format("SUCCESS", str(_))


def test_bytom_cli(cli_tester):
    assert cli_tester.invoke(cli_main.shuttle,
                             ["bytom"]).exit_code == 0

    # Testing bytom decode command.
    decode = cli_tester.invoke(cli_main.shuttle,
                               ["bytom", "decode", "--raw", FUND_RAW])
    assert decode.exit_code == 0
    assert decode.output != success("") + "\n"

    # Testing bitcoin sign command.
    fund_sign = cli_tester.invoke(cli_main.shuttle,
                                  ["bytom", "sign", "--unsigned", FUND_RAW, "--xprivate", XPRIVATE_KEY])
    assert fund_sign.exit_code == 0
    assert fund_sign.output == success(FUND_SIGNED) + "\n"

    # Testing bitcoin sign command.
    claim_sign = cli_tester.invoke(cli_main.shuttle,
                                   ["bytom", "sign", "--unsigned", CLAIM_RAW, "--xprivate", XPRIVATE_KEY])
    assert claim_sign.exit_code == 0
    assert claim_sign.output == success(CLAIM_SIGNED) + "\n"

    # Testing bitcoin sign command.
    refund_sign = cli_tester.invoke(cli_main.shuttle,
                                    ["bytom", "sign", "--unsigned", REFUND_RAW, "--xprivate", XPRIVATE_KEY])
    assert refund_sign.exit_code == 0
    assert refund_sign.output == success(REFUND_SIGNED) + "\n"

    # Testing bytom submit command.
    submit = cli_tester.invoke(cli_main.shuttle,
                               ["bytom", "submit", "--raw", REFUND_RAW])
    assert submit.exit_code == 0
    assert submit.output == "[ERROR] finalize tx fail" + "\n"
